### ISSUE TITLE
Inference problem

### ISSUE THREAD

**Issue by AlexeySrus** [Xylon-Sean/rfnet#1]
How I should preprocess image in order to get the parameters (im_data, im_info, im_raw) to feed to the RFNetSO.inference input?

I try use next preprocessing in (change) ms.py:

`model.eval()

    img = np.array(Image.open(args.image).convert('LA'))[..., 0]

    im_data = torch.Tensor(cv2.resize(img, (720, 960))).to('cuda').unsqueeze(0).unsqueeze(0) / 255
    raw_data = torch.Tensor(cv2.resize(img, (240, 320))).to('cuda').unsqueeze(0).unsqueeze(0) / 255

    #sh sw
    image_info = torch.FloatTensor([[720 / img.shape[0], 960 / img.shape[1]]]).cuda()
    #
    im_scale, kpts, im_des = model.inference(im_data, image_info, raw_data)`

**Comment by Xylon-Sean** [comment]
@AlexeySrus 
Hi, I just update code with a 'detectAndCompute' method in class RFNetSO. 
You could directly extract keypoints and descriptors by it.
