### ISSUE TITLE
Erroe:CUDA out of memory

### ISSUE THREAD

**Issue by iamwangyabin** [Xylon-Sean/rfnet#3]
Sorry, I try to run train.sh,but got this error`RuntimeError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 7.77 GiB total capacity; 6.85 GiB already allocated; 59.12 MiB free; 148.04 MiB cached)` 
My computer has two 2080 and I try to downsample images fed to model and also failed ,Would you please tell  me how to modify the program to reduce the memory usage.
Thanks a lot!

**Comment by iamwangyabin** [comment]
OK,I change to run it on Tesla P100 ,and this way success . the program is no problem ....although totally allocate memory is 10805MB so it need a better card than 2080.
But I still want to train it with my computer , Can I reduce memory use?

**Comment by Xylon-Sean** [comment]
@iamwangyabin 
Sorry for replying to your question too late.

You could change the parameter `__C.TRAIN.TOPK = 512` to `__C.TRAIN.TOPK = 256`.(The `TOPK` means the number of keypoints)
