### ISSUE TITLE
example problem

### ISSUE THREAD

**Issue by jingweixi** [Xylon-Sean/rfnet#5]

**Comment by jingweixi** [comment]
when I run the example.py with NNR match strategy and pretrained model .I find that there are many mismatch points. Please tell me why this problem occurs and how to solve it.
Thanks a lot!
![Uploading 128 43.png…]()

**Comment by Xylon-Sean** [comment]
@jingweixi 
Sorry, I found a bug in the example.py, the image input size should be (240, 320), not (320, 240), cause the network was trained under (240, 320) input size.

I updated code, you could try it again, and the result should be better.

![outImg](https://user-images.githubusercontent.com/11812431/62999603-89a7d300-bea1-11e9-9d84-8c1cad4d696f.png)

**Comment by jingweixi** [comment]
thanks！
