### ISSUE TITLE
small query

### ISSUE THREAD

**Issue by skrish13** [Xylon-Sean/rfnet#6]
Hi,

Thanks for providing the code and making it so user-friendly! I had a small query regarding the name of the pretrained weight file shared. `e121_NN_0.480_NNT_0.655_NNDR_0.813_MeanMS_0.649.pth.tar` Am I right in assuming they're the accuracies using those evaluation metrics? If so, this is on which data exactly? (HPatches? Validation? Test? V/I?) Also what is MeanMS?

**Comment by skrish13** [comment]
Also, could you share the split of train (&val) and test scenes on HPatches?

**Comment by Xylon-Sean** [comment]
@skrish13 
of course, but recently I am busy with DL, so can you wait a few more weeks?

**Comment by Xylon-Sean** [comment]
@skrish13 

The file name ```e121_NN_0.480_NNT_0.655_NNDR_0.813_MeanMS_0.649.pth.tar``` comes from the code in ```evaluate()``` function:
https://github.com/Xylon-Sean/rfnet/blob/f6b54087f27caf84103806393c166c4d78d14613/train.py#L408

You could see, we call this ```evaluate()``` function on Line 451 and send a parameter called ```val_data```
https://github.com/Xylon-Sean/rfnet/blob/f6b54087f27caf84103806393c166c4d78d14613/train.py#L423

The ```val_data``` defined on Line 214.
https://github.com/Xylon-Sean/rfnet/blob/f6b54087f27caf84103806393c166c4d78d14613/train.py#L214

Therefore, the first question is
> If so, this is on which data exactly?

The answer of this question is
> The evaluation data comes from line 236 to 265 in ```hpatch_view.csv``` 

The second question is
> what is MeanMS?

The answer is
> meanms = (PreNN + PreNNT + PreNNDR) / 3
on
https://github.com/Xylon-Sean/rfnet/blob/f6b54087f27caf84103806393c166c4d78d14613/train.py#L406

**Comment by skrish13** [comment]
This is great! Thanks for the detailed response :)
